<?php


namespace kodCommerce\frontend\controllers;


use kodCommerce\frontend\models\CartModel;


use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\Response;

class CartApiController extends Controller
{
    public function beforeAction($action)
    {
        \Yii::$app->request->parsers['application/json'] =  'yii\web\JsonParser';
        \Yii::$app->response->format = Response::FORMAT_JSON;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * @var string
     */
    protected $modelClass = CartModel::class;


    private function sendCart(){
        return $this->asJson($this->modelClass::getAll());
    }

    public function actionIndex()
    {


       return $this->modelClass::getAll();
}

    /**
     * @return \yii\web\Response
     */
    public function actionAdd()
    {
      $model = new $this->modelClass();
      $model->scenario = $model::SCENARIO_ADD;
      if($model->load(\Yii::$app->request->post()) && $model->save()){
        return  $model->data;
      }else{
          \Yii::$app->response->statusCode = 422;
         return  $this->asJson($model->getErrorSummary(true));
      }
    }

    /**
     * @return \yii\web\Response
     */
    public function actionDelete()
    {
        $model = new $this->modelClass();
        $model->setScenario($model::SCENARIO_DELETE);
        if($model->load(\Yii::$app->request->post()) && $model->delete()){
          return $this->modelClass::getAll();
        }else{
            \Yii::$app->response->statusCode = 422;
            return  $model->getErrors('sku');
        }

    }

    public function actionClear()
    {
        $this->modelClass::clear();
        return $this->sendResult("Cart Cleared");
    }

            public function send(array $data){
                   VarDumper::dump($data,10,1);

                   die;
            }

    public function sendResult($body,$type = "success",$message = "")
    {
            return [
                "status"=>$type,
                "message"=>$message,
                "body"=>$body
            ];

            }
}
